import { Project, BlogPost } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'kinetic-type',
    title: 'Kinetic Typography Study',
    category: 'Motion Design',
    year: '2026',
    description: 'An exploration of motion and rhythm through experimental letterforms.',
    image: 'https://picsum.photos/seed/kinetic/1200/800',
    content: [
      'This project explores the intersection of sound and visual rhythm. By deconstructing letterforms and reassembling them in a 3D space, we created a series of loops that respond to ambient noise levels.',
      'The challenge was to maintain legibility while pushing the boundaries of abstraction. We used a custom-built script to automate the physics-based movements of each glyph.',
    ],
    tags: ['After Effects', 'Typography', 'Experimental'],
    hindiAccent: 'क',
  },
  {
    id: 'neo-brutalist-ui',
    title: 'Neo-Brutalist Interface',
    category: 'UI/UX Design',
    year: '2025',
    description: 'A design system built on high contrast, bold borders, and raw functionality.',
    image: 'https://picsum.photos/seed/ui/1200/800',
    content: [
      'Moving away from the "soft" design trends of the last decade, this project embraces the raw aesthetics of the early web. High contrast, visible grids, and un-aliased shadows define the visual language.',
      'User testing showed that the high contrast significantly improved accessibility for users with visual impairments, while the bold hierarchy made navigation more intuitive.',
    ],
    tags: ['Figma', 'Design Systems', 'Accessibility'],
    hindiAccent: 'न',
  },
  {
    id: 'monolith-branding',
    title: 'Monolith Brand Identity',
    category: 'Branding',
    year: '2025',
    description: 'Visual identity for a sustainable architecture firm focusing on raw materials.',
    image: 'https://picsum.photos/seed/monolith/1200/800',
    content: [
      'Monolith is an architecture firm that specializes in concrete and stone. The branding needed to reflect the weight and permanence of their work.',
      'We developed a logo based on a modular grid that can be rearranged to form different architectural shapes, symbolizing the versatility of raw materials.',
    ],
    tags: ['Branding', 'Logo Design', 'Print'],
    hindiAccent: 'म',
  },
  {
    id: 'f1-redesign',
    title: 'F1 Website Redesign',
    category: 'UI/UX Design',
    year: '2026',
    description: 'A high-performance digital experience for the pinnacle of motorsport.',
    image: 'https://picsum.photos/seed/f1/1200/800',
    content: [
      'The current F1 digital ecosystem is data-rich but often overwhelming. This redesign focuses on high-speed information delivery and immersive storytelling.',
      'By using a modular grid system inspired by telemetry data, we created a layout that feels as fast as the cars on track.',
    ],
    tags: ['F1', 'UI/UX', 'Speed'],
    hindiAccent: 'फ़',
  },
  {
    id: 'nexus-rebranding',
    title: 'Nexus Rebranding',
    category: 'Branding',
    year: '2026',
    description: 'Redefining visual identity for a tech-forward logistics startup.',
    image: 'https://picsum.photos/seed/nexus/1200/800',
    content: [
      'Nexus needed a brand that communicated both reliability and innovation. We developed a visual system based on "connected paths."',
      'The new identity uses a bold, custom typeface and a high-contrast color palette to stand out in a crowded logistics market.',
    ],
    tags: ['Branding', 'Identity', 'Strategy'],
    hindiAccent: 'न',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'the-power-of-negative-space',
    title: 'The Power of Negative Space',
    date: 'March 15, 2026',
    excerpt: 'How silence in design can speak louder than noise. Exploring the balance of emptiness.',
    image: 'https://picsum.photos/seed/space/800/600',
    content: [
      'Negative space is not empty space. It is a deliberate choice to let the core message breathe. In a world of constant visual noise, the ability to use "nothing" effectively is a designer\'s greatest asset.',
      'When we look at brutalist architecture, we see massive forms, but it\'s the space between those forms that defines the scale. The same applies to digital interfaces.',
    ],
    tags: ['Design Theory', 'Minimalism'],
    readTime: '4 min read',
    hindiAccent: 'प',
  },
  {
    id: 'why-brutalism-is-returning',
    title: 'Why Brutalism is Returning',
    date: 'February 28, 2026',
    excerpt: 'A look at the cyclical nature of design trends and the rejection of "safe" aesthetics.',
    image: 'https://picsum.photos/seed/brutal/800/600',
    content: [
      'We are seeing a massive shift away from the rounded, soft, "friendly" UI of the late 2010s. Designers are craving something more honest, more raw.',
      'Brutalism in web design isn\'t just about being "ugly" or "hard to use." It\'s about transparency of structure and a rejection of unnecessary decoration.',
    ],
    tags: ['Trends', 'Brutalism', 'Web Design'],
    readTime: '6 min read',
    hindiAccent: 'व',
  },
  {
    id: 'faith-or-superstition',
    title: 'Faith or Superstition?',
    date: 'April 5, 2026',
    excerpt: 'Observations from a temple where cigarettes are offered to the divine.',
    image: 'https://picsum.photos/seed/temple/800/600',
    content: [
      'Recently, I visited a temple where people offer cigarettes to God. It sparked a deep thought about the thin line between faith (Aastha) and superstition (Andhvishwas).',
      'Is it the offering that matters, or the belief behind it? In design, we often face similar dilemmas—what is essential and what is just a ritual? Sometimes, the most unconventional choices are the ones that carry the most meaning.',
    ],
    tags: ['Philosophy', 'Culture', 'Observations'],
    readTime: '5 min read',
    hindiAccent: 'फ़',
  },
  {
    id: 'tedx-design-head',
    title: 'Leading Design at TEDx',
    date: 'March 20, 2026',
    excerpt: 'My journey as the Design Head for this year\'s TEDx event.',
    image: 'https://picsum.photos/seed/tedx/800/600',
    content: [
      'Serving as the Design Head for TEDx this year was a whirlwind of creativity and coordination. From stage design to digital assets, every touchpoint needed to reflect the theme of "Uncharted Territories."',
      'It taught me the importance of visual consistency in large-scale events and how design can shape the entire attendee experience.',
    ],
    tags: ['Leadership', 'Event Design', 'TEDx'],
    readTime: '7 min read',
    hindiAccent: 'ल',
  },
  {
    id: 'beauty-of-imperfection',
    title: 'The Beauty of Imperfection',
    date: 'March 10, 2026',
    excerpt: 'Why "perfect" design can sometimes feel soulless.',
    image: 'https://picsum.photos/seed/imperfection/800/600',
    content: [
      'We often strive for pixel-perfection, but sometimes it\'s the slight irregularities that give a design its soul.',
      'Wabi-sabi in the digital age is about embracing the human touch in an automated world. A slightly "off" alignment or a hand-drawn element can create a much stronger emotional connection than a sterile, perfect layout.',
    ],
    tags: ['Aesthetics', 'Wabi-sabi', 'Design Philosophy'],
    readTime: '3 min read',
    hindiAccent: 'ब',
  },
];
